#!/bin/bash

##
# Utility bar core script
# This is the main script used for the config which calls and sources all the helpers and Plugins / Items.
# Made by @kcraft059
##

# --- Sourcing of core scripts + Initial setup config ---
RELPATH="$(dirname "$0")"
OS_VERSION="$(sw_vers -productVersion)"

export PATH="/opt/homebrew/bin:/opt/homebrew/sbin:/run/current-system/sw/bin:/nix/var/nix/profiles/default/bin:$PATH"
mkdir -p "${TMPDIR}sketchybar"

## Optional user configuration
if [[ -n "$SKETCHYBAR_CONFIG" && -f "$SKETCHYBAR_CONFIG" ]]; then
	# External override path (useful for Nix)
	# shellcheck disable=SC1090
	source "$SKETCHYBAR_CONFIG"
elif [[ -f "$RELPATH/config.sh" ]]; then
	# Local config file in repository
	# shellcheck disable=SC1091
	source "$RELPATH/config.sh"
fi

## Fallback defaults if variables unset
: "${NOTCH_WIDTH:=180}"                                      # <int>
: "${MUSIC_INFO_WIDTH:=80}"                                  # <int>
: "${CPU_UPDATE_FREQ:=2}"                                    # <int>
: "${MENUBAR_AUTOHIDE:=True}"                                # <true|false>
: "${GITHUB_TOKEN:="~/.github_token"}"                       # <path>
: "${WIFI_UNREDACTOR:="~/Applications/wifi-unredactor.app"}" # <path>
: "${BAR_LOOK:="plain"}"                                     # <"plain"|"compact">
: "${HIDE_EMPTY_SPACES:="false"}"                            # <true|false> / Is not really used here but rather in the scripts.sh

[ ${#MENU_CONTROLS[@]} -eq 0 ] && MENU_CONTROLS=(
	"Control__Center,Bluetooth"
)

## WM detect if not already defined
if [ -z $WINDOW_MANAGER ]; then
	if command -v rift-cli >/dev/null; then WINDOW_MANAGER="rift"; fi
	if command -v aerospace >/dev/null; then WINDOW_MANAGER="aerospace"; fi
	if command -v yabai >/dev/null; then WINDOW_MANAGER="yabai"; fi
fi

## Helpers sourcing
source "$RELPATH/log_handler.sh"
source "$RELPATH/set_colors.sh"
source "$RELPATH/icon_map.sh"
source "$RELPATH/add_separator.sh"

# --- Bar & Default Properties ---
sendLog "=== Loading sketchybar config... ===" "info"
sendLog "" "info"

# Notify when no window-manager
if [ -z $WINDOW_MANAGER ]; then
	sendErr "No Window-Manager detected, defaulting to yabai. (This will likely cause problems)" "info"
	WINDOW_MANAGER="yabai"
fi

if [ $(echo $OS_VERSION | awk -F. '{print $1}') -gt 15 ]; then
	sendWarn "You are on a macOS version greater than macOS 15.x ($OS_VERSION), some features might not work properly" "info"
fi

[[ -f ./dyn-icon_map.sh ]] && sendLog "Found dyn-icon_map.sh, using instead." "vomit"

command -v 'menubar' 2>/dev/null 1>&2 || sendWarn "Binary \`menubar\` not in \$PATH, using bundled version" "debug"
menubarImportCmd="command -v 'menubar' 2>/dev/null 1>&2 || alias menubar=\"$RELPATH/menubar\""

FONT="JetBrainsMono Nerd Font"
OUTER_PADDINGS=5
INNER_PADDINGS=5
X_BAR_PADDING=12

case ${BAR_LOOK} in
"plain")
	BAR_HEIGHT=34
	BAR_MARGIN=5
	;;
"compact")
	BAR_HEIGHT=27
	;;
esac

if [ "$(echo "$OS_VERSION" | awk -F. '{print $1}')" -gt 15 ]; then
	BAR_CORNER_RADIUS=15
else
	BAR_CORNER_RADIUS=13
fi

bar=(
	height=$BAR_HEIGHT
	y_offset=$BAR_MARGIN
	margin=$BAR_MARGIN
	#shadow=on
	#shadow.color=$SHADOW_COLOR
	#shadow.angle=45
	#shadow.distance=2
	padding_left=0
	padding_right=$X_BAR_PADDING
	color="$BAR_COLOR"
	border_width=1
	border_color=$BORDER_COLOR
	corner_radius=$BAR_CORNER_RADIUS
	blur_radius=15
	notch_width=$NOTCH_WIDTH
)

defaults=(
	updates=when_shown
	icon.font="$FONT:Regular:14.0"
	icon.color=$ICON_COLOR
	padding_left=$OUTER_PADDINGS
	padding_right=$OUTER_PADDINGS
	icon.padding_left=$INNER_PADDINGS
	icon.padding_right=$INNER_PADDINGS
	label.font="$FONT:Bold:13.0"
	label.color=$LABEL_COLOR
	label.padding_left=$INNER_PADDINGS
	label.padding_right=$INNER_PADDINGS
	background.corner_radius=8
	popup.y_offset=4
	popup.background.border_width=1
	popup.background.corner_radius=6
	popup.background.border_color=$POPUP_BORDER_COLOR
	popup.background.color=$POPUP_BACKGROUND_COLOR
	popup.blur_radius=20
	popup.background.shadow.drawing=on
)

zones=(
	background.height=$(($BAR_HEIGHT - 8))
	background.border_width=2
	background.border_color=$HIGH_MED
	background.color=$OVERLAY
	background.corner_radius=8
	blur_radius=24
)

sketchybar --bar "${bar[@]}"
sketchybar --default "${defaults[@]}"

# --- Bar Items ---

sendLog "Starting sourcing of Items..." "vomit"

source "$RELPATH/sketchy-items/logo.sh"
source "$RELPATH/sketchy-items/spaces.sh"
source "$RELPATH/sketchy-items/frontapp.sh"
source "$RELPATH/sketchy-items/menus.sh"
source "$RELPATH/sketchy-items/calendar.sh"
source "$RELPATH/sketchy-items/mic.sh"
source "$RELPATH/sketchy-items/volume.sh"
source "$RELPATH/sketchy-items/battery.sh"
source "$RELPATH/sketchy-items/wifi.sh"
source "$RELPATH/sketchy-items/display.sh"
source "$RELPATH/sketchy-items/more-menu.sh"
source "$RELPATH/sketchy-items/packages.sh"
source "$RELPATH/sketchy-items/currentuser.sh"
source "$RELPATH/sketchy-items/notifications.sh"
source "$RELPATH/sketchy-items/controls.sh"

source "$RELPATH/sketchy-items/music.sh"
source "$RELPATH/sketchy-items/cpu.sh"

sendLog "Finished sourcing of Items" "vomit"

sketchybar --add bracket base-controls battery wifi display \
	--set base-controls "${zones[@]}" \
	--add bracket volume_controls volume_icon mic \
	--set volume_controls "${zones[@]}" \
	--add bracket more_menu '/moremenu\..*/' "${menuitem[@]}" \
	--set more_menu "${zones[@]}"

sketchybar --update


sendLog "" "info"
sendLog "=== Sketchybar configuation loaded ===" "info"
